version: "3"
services:
  app:
    build: .
    ports:
      - 5000:5000
    environment:
      PORT: 5000
    volumes:
      - ./neural-recognition-frontend/build:/usr/app/neural-recognition-frontend/build
